version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./.containers/db:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_REGISTRY-}backend
    container_name: backend
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
